### ISSUE TITLE
Not readable with devtools using dark theme

### ISSUE THREAD

**Issue by cschleiden** [abettadapur/redux-saga-devtools-extension#1]
![image](https://user-images.githubusercontent.com/2201819/42200280-5acf6dcc-7e47-11e8-93ec-f461dc9bfaff.png)

**Comment by abettadapur** [comment]
Thanks @cschleiden, will investigate :)

**Comment by abettadapur** [comment]
Fixed by 7c4324

**Comment by cschleiden** [comment]
Looks great, thanks
