### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by cschleiden** [abettadapur/redux-saga-devtools-extension#2]
Somehow that arrow is not being displayed for me:

![image](https://user-images.githubusercontent.com/2201819/42200320-8cf7a062-7e47-11e8-8288-a5624c7a7788.png)

**Comment by alexbaumgertner** [comment]
Seems like bug is here: https://github.com/redux-saga/redux-saga-devtools/blob/master/src/components/Effect/Result.js#L31
