### ISSUE TITLE
Some sagas show up as unknown

### ISSUE THREAD

**Issue by cschleiden** [abettadapur/redux-saga-devtools-extension#3]
The `yield all` now shows up correctly, but the sagas I pass to `all` show up as `unknown`:

![image](https://user-images.githubusercontent.com/2201819/42259015-6c0f828a-7f13-11e8-8e27-303e22adf462.png)

**Comment by abettadapur** [comment]
Fixed in 0.0.5

**Comment by jaebradley** [comment]
@abettadapur I'm seeing this behavior on `0.0.6`

![image](https://user-images.githubusercontent.com/8136030/46967706-29b88400-d066-11e8-8c15-7282896fe280.png)


![image](https://user-images.githubusercontent.com/8136030/46967658-11e10000-d066-11e8-9ddc-8cbc9f3e1404.png)

Any guidance?
